version: "3.8"

services:
  # -----------------------------
  # PostgreSQL
  # -----------------------------
  postgres:
    image: postgres:15
    container_name: traffic_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  # -----------------------------
  # MinIO
  # -----------------------------
  minio:
    image: minio/minio
    container_name: traffic_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./minio/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always

  # -----------------------------
  # Airflow INIT
  # -----------------------------
  airflow-init:
    image: apache/airflow:2.9.0
    container_name: traffic_airflow_init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${DB_PASSWORD}@traffic-risk-postgres.cgf4cckuyhc9.us-east-1.rds.amazonaws.com:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__PIP_ADDITIONAL_REQUIREMENTS: "boto3 requests pandas pyarrow"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    entrypoint:
      - /bin/bash
      - -c
      - |
        airflow db migrate && \
        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password admin
    restart: "no"

  # -----------------------------
  # Airflow Webserver
  # -----------------------------
  airflow-webserver:
    image: apache/airflow:2.9.0
    container_name: traffic_airflow_webserver
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__WEBSERVER__WEB_SERVER_TIMEOUT: "300"
      AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT: "300"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${DB_PASSWORD}@traffic-risk-postgres.cgf4cckuyhc9.us-east-1.rds.amazonaws.com:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__PIP_ADDITIONAL_REQUIREMENTS: "boto3 requests pandas pyarrow"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

    user: 0:0
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    command: webserver
    restart: always

  # -----------------------------
  # Airflow Scheduler
  # -----------------------------
  airflow-scheduler:
    image: apache/airflow:2.9.0
    container_name: traffic_airflow_scheduler
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${DB_PASSWORD}@traffic-risk-postgres.cgf4cckuyhc9.us-east-1.rds.amazonaws.com:5432/airflow
      AIRFLOW__PIP_ADDITIONAL_REQUIREMENTS: "boto3 requests pandas pyarrow"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    user: 0:0
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock

    command: scheduler
    restart: always

  # -----------------------------
  # Jupyter
  # -----------------------------
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: traffic_jupyter
    depends_on:
      - minio
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    command:
      - /bin/bash
      - -c
      - |
        pip install --quiet boto3 pyarrow && \
        start-notebook.py --NotebookApp.token=traffic --NotebookApp.password=''
    restart: always

  # -----------------------------
  # Superset INIT
  # -----------------------------
  superset-init:
    build: ./superset
    container_name: traffic_superset_init
    environment:
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      DB_PASSWORD: ${DB_PASSWORD}
    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10
        superset db upgrade
        superset fab create-admin \
          --username admin \
          --firstname Admin \
          --lastname User \
          --email admin@local \
          --password admin
        superset init
    volumes:
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py

  # -----------------------------
  # Superset APP
  # -----------------------------
  superset:
    build: ./superset
    container_name: traffic_superset
    depends_on:
      - superset-init
    environment:
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8088:8088"
    command: >
      /bin/bash -c "superset run -h 0.0.0.0 -p 8088"
    volumes:
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py
    restart: always

    
  pgadmin:
    image: dpage/pgadmin4
    container_name: traffic_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    restart: always

  
  dbt:
    build: ./dbt
    container_name: traffic_dbt
    volumes:
      - ./dbt:/app

volumes:
  postgres_data: